coin3d/coin

CMakeLists.txt
examples/bindings/glxiv.cpp
include/Inventor/SbBasic.h
src/fonts/freetype.cpp
src/glue/freetype.cpp
src/glue/freetype.h

This PR incorporates patches from Fedora, Rosa, and Gentoo distributions.

Incorporating dist patches

---

src/base/SbBox2d.cpp
src/base/SbBox2f.cpp
src/base/SbBox3d.cpp
src/base/SbBox3f.cpp
src/base/SbBox3i32.cpp
src/base/SbBox3s.cpp

Fix incorrect closest point calculation for bounding boxes.

---

src/shapenodes/SoFaceSet.cpp

Fix for incorrect rendering of SoFaceSet. Conditions when to render as VertexArrayObject were not properly checked.

Fix for incorrect rendering of SoFaceSet

---

src/elements/GL/SoGLMultiTextureImageElement.cpp

Added GL error checking for debug mode.

---

README.MACOSX
scripts/findNecessaryBoostIncludes.sh
src/3ds/SoStream.h
src/bundles/SoTextureCoordinateBundle.cpp
src/draggers/SoDragger.cpp
src/fonts/glyph2d.cpp
src/fonts/glyph3d.cpp
src/nodes/SoNode.cpp
src/sensors/SoSensor.cpp
src/sensors/SoSensorManager.cpp
src/shaders/SoShaderObject.cpp
src/xml/path.cpp
test-code/mt-attack/mt-output-attack.cpp.in

Fix various typos/grammar

---

.github/workflows/continuous-integration-workflow.yml
src/shadows/SoShadowGroup.cpp

Fix Shadow issues for Intel Graphics HD 630

---

src/shadows/SoShadowGroup.cpp

Fix testing for maximum texture size

---

src/nodes/SoNode.cpp

Fix doc for SbUniqueId

---

CMakeLists.txt

Do not run programs for determining hash quoting

---

configure
configure.ac
src/xml/expat/all-expat-c.c

Fix linking with system installation of expat.

---

README.md
docs/Coin3DElements.svg

Readme: Switch to Markdown, add a diagram

---

README.md

Closes #164  
Preview: https://github.com/luzpaz/coin/tree/repology/README.md

README: add small repology badge

---

src/fonts/builtin2dfonts.icc
src/fonts/default3dfont.cpp
src/fonts/freetype.cpp
src/shapenodes/SoMarkerSet.cpp

see https://randomascii.wordpress.com/2017/01/08/add-a-const-here-delete-a-const-there

Move constant data to read only data segment

---

src/rendering/SoGL.cpp
src/shapenodes/SoIndexedLineSet.cpp

Fixed material and normal handling for indexed line set

---

src/threads/mutex.cpp

Optimize mutex debugging

---

src/nodes/SoTransform.cpp

Minor optimization to avoid needless matrix multiplications.

---

src/io/SoInput.cpp
src/misc/SoJavaScriptEngine.cpp
src/nodes/SoTexture3.cpp
src/shadows/SoShadowGroup.cpp

Special thanks goes to @0xacb @nahamsec making us aware of the issue.

Fix format string vulnerabilities.

---

src/lists/SoCallbackList.cpp

Fix invalid access when removing callback.

---

src/glue/gl.cpp

Fix regression due to removed cc_glglue initialization.

---

src/vrml97/Background.cpp

Fixed crash in SoVRMLBackground::GLRender due to unchecked ptr

---

examples/CMakeLists.txt
examples/sdl3/CMakeLists.txt
examples/sdl3/sdl3.cpp

This PR adds an example to demonstrate how to use coin3d along with the SDL3 library. The code is based on the glfw example.
I have only tested this on linux.

Add sdl3 example
